name:  Whatsapp Notify
on:
  pull_request:
    types: [opened,closed]
  issues:
    types: [opened, closed]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wa-Notify
        uses: mdb571/wa-action@master
        with:
          from: ${{ secrets.FROM }}
          to: ${{secrets.TO }}
          twilio_api: ${{ secrets.TWILIO_API }}
          twilio_auth: ${{ secrets.TWILIO_AUTH }}
        